version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: homeworkPass
      POSTGRES_USER: homeworkUser
      POSTGRES_DB: homeworkDB
    volumes:
      - homeworkData:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  homeworkData: